[package]
name = "ed25519-compact"
version = "0.1.0"
authors = ["Frank Denis <github@pureftpd.org>"]
edition = "2018"
description = "A small, self-contained, wasm-friendly Ed25519 implementation"
readme = "README.md"
keywords = ["crypto", "ed25519", "eddsa", "signature"]
repository = "https://github.com/jedisct1/rust-ed25519-compact"
homepage = "https://github.com/jedisct1/rust-ed25519-compact"
categories = ["algorithms", "cryptography", "no-std", "wasm"]
license = "ISC"

[features]
default = ["std", "random"]
self-verify = []
std = []
random = ["getrandom"]

[dependencies]
getrandom = { version = "0.1", optional = true }

[dev-dependencies]
getrandom = "0.1"