name: GitHub CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Build with nostd
      run: cargo build --verbose --no-default-features
    - name: Build with extra features
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose
